name: pull-request-on-master
run-name: Terraform plan on pull request on master branch
on:
  pull_request:
    branches:
      - master

jobs:
  tf_plan:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - name: Print variable
        run: echo ${{ vars.TEST_VARIABLE }}

      - name: Print secret
        run: echo ${{ secrets.TEST_SECRET }}

      - name: Is secret there
        if: ${{ secrets.TEST_SECRET == 'Secret text' }}
        run: echo "Yes we see the secret"
